export const paths = {
  welcome: '/welcome',
  login: '/login',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  updatePassword: '/first-access',
  home: '/',
  alerts: '/alerts',
  serviceOrders: '/service-orders',
  relocations: '/relocations',
  branches: '/branches',
  employees: '/employees',
  employeeCreate: '/employees/new',
  metrics: '/metrics',
} as const